# language target
language: cpp
compiler: gcc

name: "Bionic Ubuntu Linux"
os: linux
dist: bionic
sudo: required

addons:	
  apt:	
    sources:	
        - sourceline: 'ppa:beineri/opt-qt-5.13.2-bionic'	
    packages:         
      - make	
      - qt513base	
      - qt513tools	
      - qt513multimedia	
      - libogg-dev	
      - libopus-dev
      -	libgl1-mesa-dev

script: 
  - source /opt/qt513/bin/qt513-env.sh
  - qmake ./ultracopier.pro
  - make -j$(nproc)
  
# deploy to Github
deploy:
  # deploy on linux
  provider: releases
  skip_cleanup: true
  github_token: $GITHUB_TOKEN   
  keep_history: true
  on:
    branch: master
